### ISSUE TITLE
Err 4, Linker Ram section should be at 20004978, len b688

### ISSUE THREAD

**Issue by jjduhamel** [mwaylabs/fruitymesh#116]
Hi.

When I try to compile and flash the new version of fruitymesh, the device prints the following error then reboots.

  “Err 4, Linker Ram section should be at 20004978, len b688”

Interestingly, when I flash the device with `binary/fruitymesh_nrf52_s132.hex`, the device functions properly.  I tried debugging the linker script, but the relevant parts look identical to the previous version which I had working.  Could you possibly give some guidance to debug this issue?

**Comment by MichalBiolik** [comment]
Hello,

Thank you for pointing out this error. The fix is very simple. Please go to file `Makefile.NRF52`.  Replace line 58 (`SOFTDEVICE_PATH = $(COMPONENTS)/softdevice/s132/hex/s132_nrf52_5.0.0_softdevice.hex`) with this line:
`SOFTDEVICE_PATH = softdevice/s132_nrf52_5.1.0_softdevice.hex`
Note that this version is different then one used by default.

Regards
