### ISSUE TITLE
ERROR: Argument provided has a wrong value. Memory access not aligned, value outside of range or similar.

### ISSUE THREAD

**Issue by jjduhamel** [mwaylabs/fruitymesh#121]
After pulling the latest changes, I'm getting the following error when I try to flash my device.

```
$ make flash
Flashing: _build/release/NRF52832/github/FruityMesh.hex + softdevice
Parsing input hex files.
Merging files.
Storing merged file.
ERROR: Argument provided has a wrong value. Memory access not aligned, value
ERROR: outside of range or similar.
make: *** [flash] Error 54
```

I notice you removed Makefile.NRF52.  Previously, I was flashing the binary produced by this makefile.

```
$ make flash
Flashing: _build/release/NRF52/github/FruityMesh.hex + softdevice
Parsing input hex files.
Merging files.
Storing merged file.
Parsing hex file.
Erasing user available code and UICR flash areas.
Applying system reset.
Checking that the area to write is not protected.
Programming device.
Applying system reset.
Run.
```

**Comment by mariusheil** [comment]
Hi, it looks like the family parameter was incorrectly passed to the script. We are internally using a custom deployment tool, so that slipped through.
I pushed a new commit that fixed it.
The makefiles have been renamed as NRF52 does refer to a few different chipsets, so we are now always using the platform, e.g. NRF52832. This is more consistent with how nordic names their chipsets.
Feel free to reopen the issue, if it does not work.
