### ISSUE TITLE
bsp.c linker issue

### ISSUE THREAD

**Issue by Dan-Thies** [mwaylabs/fruitymesh#41]
Hi there,
I am a Senior in college and I have been looking into using your mesh for a project. I had noticed that there are not any physically driven interrupts native to the code that you have created; everything is done through terminal. So I had tried to create a button interrupt for the pca10036 nordic dev kit through the SDK bsp.c This C file provides the functions of bsp_init() and bsp_event_to_button_action_assign() to use. My issue comes when I try to compile the project. The eclipse linker constantly throws errors stating that the bsp.h and bsp.c cannot be found. I was wondering if there was any special way that I needed to go about linking these files? Along with that is there a better way to go about setting up GPIO and button pin interrupts?

**Comment by mariusheil** [comment]
Hello,

sorry for overlooking your question. I did not make use of interrupts because I do most activity timer based. Have you included the bsp files correctly in the project? I want to include some button interrupt myself, but have not yet done so, but by looking at the examples I haven't myself found a best-practice for including a button interrupt.
