### ISSUE TITLE
Sniffing Packets

### ISSUE THREAD

**Issue by junaediadi** [mwaylabs/fruitymesh#54]
Dear Marius,

Is it possible to know/calculate all packets that has been sent or received including the advertisement packet and data packet in Fruity Mesh?

Sincerely yours,
Junaedi Adi Prasetyo

**Comment by mariusheil** [comment]
Hi,

the Connection class has counters for sentReliable and sentUnreliable bot none for received packets yet. Counting sent advertisement packets is hard because you don't know how the Softdevice scheduler works and therefore how often it will advertise. And even then you wouldn't know if other nodes received your packet on the advertisement channels. For received advertisement packets, there's also no counter in the current release, but you can count yourself by using the BLE_GAP_EVT_ADV_REPORT event in your module or anywhere else. Another method would be using the radio_notification_listener. But this one doesn't give you the type of radio activity that has been going on, so you have to do a lot of guessing.
