### ISSUE TITLE
Do All nodes know about other nodes ?

### ISSUE THREAD

**Issue by anujdutt9** [mwaylabs/fruitymesh#58]
Hi. I have 4 nrf51 dongle and was playing around with them using the fruity mesh. One thing that I noticed is that once the mesh is formed, each node only has information of the other node to which it is directly connected. Is there a way to let each node know about what all nodes are present in the mesh ? Is there any command you have for that ?
Thanks : )

**Comment by mariusheil** [comment]
This information isn't saved on the nodes because depending of the size of the mesh, this would consume too much memory. This was a design choice. In case you need to know all the other nodes, try the commands action 0 status get_status or action 0 status get_device_info. This will instruct all nodes to send their status or device info to the requesting node.
But this is all described in the wiki, please do have a look at all the information that is available because I have limited time to answer questions.
