### ISSUE TITLE
Can the Advertisement Channel be Changed ?

### ISSUE THREAD

**Issue by anujdutt9** [mwaylabs/fruitymesh#65]
@mariusheil  Hi Marius. I am reading the code and in the file "Config.h", I see that under "ADVERTISING" you define three advertising channels (37,38,39) with values. It seems that currently its only using channel 37 and not the rest of the two. Is  there any reason why the rest of the two have not been used. 
Can all three of them be used to advertise the data one after the other so as to add more number of connecting nodes(peripherals) ?
Thanks : )

**Comment by mariusheil** [comment]
Hello,
I chose this advertising channel so that it is easier for a sniffer to follow a connection request between two beacons. But you can enable the other ones as well. This will increase the robustness if one of the frequencies is jammed with other signals. This does not have anything to do with peripheral connections.
