### ISSUE TITLE
How to achieve uA power level

### ISSUE THREAD

**Issue by asoftplus** [mwaylabs/fruitymesh#91]
Dear all, 

When I use the unmodified FruityMesh code, my chip's current usage level is about 0.9mA. 

(I have already commented the extra ChangeState(discoveryState::DISCOVERY_HIGH) line in the Node::ChangeState function.)

What should I do in order to achieve the current level of, for example, 240uA? 

(I have already tried to create a Low Discovery mode based on the parameters in the Battery Comsumption page. But the current comsumption was still high as before.)

Thanks for your attention.

**Comment by mariusheil** [comment]
Hi,

the best thing is to define some state in which all nodes are connected and
then switch discovery off. This will save the most energy. This can be done
by a meshgateway. If you don't use one, you have to put that logic in the
mesh (e.g. choose that the clusterSize must be 10 and switch off when the
mesh was stable for an amount of time.

You can also modify the values for the low discovery state (scan interval,
advertising interval, connectionTimeout, etc.. This is a little tricky in
the current version and needs some experimentation. You will have to choose
a connectionTimeout that is long enough so that it can pick up other nodes
if they are advertising very rarely.

The low discovery state is only chosen after the node used the high
discovery state for "discoveryHighToLowTransitionDuration" times without
finding any other node that it could connect to. This ensures that it has
enough time to find other nodes. As soon as it discovers an unconnected
node in the LOW DISCOVERY state it will switch back to HIGH discovery.

Hope this explains it a little. Just activate the logging for STATES and
see which state is used at what time.

2017-09-28 10:01 GMT+02:00 asoftplus <notifications@github.com>:

**Comment by asoftplus** [comment]
Thanks a lot for the details . 

I will try it next week.

**Comment by edwardcchan** [comment]
Hi,
We have tried to disable the discovery state but no luck. The average current is still around 1-2mA. We suspect that the modules is a bit different from yours. May I know the brand of the BLE modules you are using? Thanks alot

**Comment by mariusheil** [comment]
We are internally using a custom module, but here are the main things you
should consider:
- Make sure that UART is disabled as this has a high current usage. If you
set the uart rx/tx pin to -1 in the config, it should be switched off for
sure.
- Make sure you reset the board after flashing it as it will have a higher
current usage after being connected to a debugger
- Do some current measurements while advertising / being in a connection
without the mesh,.. (Have a look at a function called sth. like TestBattery
(some code changes needed)
- Depending on your battery supply and the LDO / DCDC circuit you will get
different results.
- compile without logging as this will produce some overhead.

2017-10-03 8:57 GMT+02:00 edwardcchan <notifications@github.com>:

**Comment by asoftplus** [comment]
Thanks a lot for your valuable details. 

I have turned off discovery and UART. The current usage has dropped from ~ 1.5mA to ~0.05mA.
